/*
 *  Sugar Custom 2016.11.16
 *
 *  has pluralize, underscore, dasherize, camelize
 * ---------------------------- */
(function(){'use strict';function n(a,b){for(var c in a)if(p(a,c)&&!1===b.call(a,a[c],c,a))break}function E(a){function b(a,b,c){l(d,a,function(a,k,P){a=x(a,k,P);Q(d,a.methods,b,c,a.a);return d})}var c="Object"===a,d=F(a);b("defineStatic",1);b("defineInstance",2);b("defineInstanceAndStatic",3);b("defineStaticWithArguments",1,!0);b("defineInstanceWithArguments",2,!0);l(d,"defineStaticPolyfill",function(b,c,d){b=x(b,c,d);u(t[a],b.methods,!0,b.a)});l(d,"defineInstancePolyfill",function(b,c,e){b=x(b,c,e);u(t[a].prototype,
b.methods,!0,b.a);n(b.methods,function(a,b){r(d,b,a)})});l(d,"alias",function(a,b){var c=d,k="string"===typeof b?d[b]:b;c[a]=k;k.instance&&r(c,a,k.instance)});l(d,"extend",function(b){function k(a,c){var d=b[a];if(d)for(var k=0,f;f=d[k];k++)if(f===c)return!0;return!1}function e(a,c,d){if(!c[a]||!d)return!1;for(a=0;a<d.length;a++)if(!1===b[d[a]])return!0}var f=t[a],h=f.prototype,m={},r={},q;b=b||{};q=b.methods;if(!k("except",f)&&(!b.namespaces||k("namespaces",f)))return c&&"boolean"===typeof b.objectPrototype&&
(y=b.objectPrototype),n(q||d,function(a,b){q&&(b=a,a=d[b]);!p(a,"instance")||c&&h===h&&(!y||"get"===b||"set"===b)||e(b,h,a.flags)||k("except",b)||(r[b]=a.instance);!p(a,"static")||c&&f===h&&(!y||"get"===b||"set"===b)||e(b,f,a.flags)||k("except",b)||(m[b]=a)}),u(f,m),u(h,r),q||l(d,"active",!0),g});q[a]=d;G["[object "+a+"]"]=d;z(a);R(d);return g[a]=d}function S(){return"Sugar"}function Q(a,b,c,d,k){n(b,function(b,f){var e,g=b;d&&(g=H(b));k&&(g.flags=k);c&2&&!b.instance&&(e=d?H(b,!0):T(b),l(g,"instance",
e));c&1&&l(g,"static",!0);e=g;a[f]=e;e.instance&&r(a,f,e.instance);a.active&&a.extend(f)})}function x(a,b,c){var d;"string"===typeof a?(d={},d[a]=b,a=c):(d=a,a=b);return{a:a,methods:d}}function H(a,b){var c=a.length-1-(b?1:0);return function(){var d=[],k=[],f;b&&d.push(this);f=Math.max(arguments.length,c);for(var e=0;e<f;e++)e<c?d.push(arguments[e]):k.push(arguments[e]);d.push(k);return a.apply(this,d)}}function T(a){switch(a.length){case 0:case 1:return function(){return a(this)};case 2:return function(b){return a(this,
b)};case 3:return function(b,c){return a(this,b,c)};case 4:return function(b,c,d){return a(this,b,c,d)};case 5:return function(b,c,d,e){return a(this,b,c,d,e)}}}function u(a,b,c,d){n(b,function(b,e){c&&!d&&a[e]||l(a,e,b)})}function F(a){function b(a,d){if(!(this instanceof b))return new b(a,d);this.constructor!==b&&(a=this.constructor.apply(a,arguments));this.raw=a}l(b,"toString",function(){return"Sugar"+a});l(b.prototype,"valueOf",function(){return this.raw});return b}function r(a,b,c){c=U(c);var d,
e,f;f=I.prototype;e=(d=f[b])&&d!==Object.prototype[b];d&&d.b||(f[b]=e?V(b):c);a.prototype[b]=c;a===g.Object&&W(b,c)}function R(a){n(g.Object&&g.Object.prototype,function(b,c){if("function"===typeof b){var d=a.prototype;p(d,c)||(d[c]=b)}})}function W(a,b){n(q,function(c){c=c.prototype;p(c,a)||(c[a]=b)})}function U(a){return function(){return new I(a.apply(this.raw,arguments))}}function V(a){function b(){var b=this.raw,d;null!=b&&(d=G[v(b)]);d||(d=g.Object);d=(new d(b))[a];if(d.b)throw new TypeError("Cannot resolve namespace for "+
b);return d.apply(this,arguments)}b.b=!0;return b}function z(a,b){var c=q[a],d=t[a].prototype;!b&&J&&(b=J(d));n(b,function(a){if("constructor"!==a&&"valueOf"!==a&&"__proto__"!==a){try{var b=d[a];if("function"!==typeof b)return}catch(fa){return}r(c,a,b)}})}function X(a,b,c){a[b]=c.value}function l(a,b,c,d){A(a,b,{value:c,enumerable:!!d,configurable:!0,writable:!0})}function v(a){return Y.call(a)}function p(a,b){return!!a&&Z.call(a,b)}function B(a,b){if(p(a,b))return a[b]}function K(a,b){var c;c||(c=
v(a));return c==="[object "+b+"]"}function aa(a,b){var c=[],d;for(d in a)d>>>0==d&&4294967295!=d&&d>=b&&c.push(+d);c.sort(function(a,c){var d=a>b;return d!==c>b?d?-1:1:a-c});return c}function L(a,b){for(var c=0,d=a.length;c<d;c++){if(!(c in a)){for(var d=a,e=b,c=aa(d,c),f,g=0,h=c.length;g<h;g++)f=c[g],e.call(d,d[f],f,d);break}b(a[c],c)}}function C(a){var b=h.acronyms&&h.acronyms.reg;return a.replace(/[-\s]+/g,"_").replace(b,function(a,b){return(0<b?"_":"")+a.toLowerCase()}).replace(/([A-Z\d]+)([A-Z][a-z])/g,
"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").toLowerCase()}function ba(a,b){a=C(a);return a.replace(ca,function(a,d,e,f){a=!1!==b||0<f;(d=h.acronyms&&h.acronyms.find(e))&&a?e=d:a&&(e=e.toLowerCase(),e=e.charAt(0).toUpperCase()+e.slice(1));return e})}function f(a,b){b=b||a;h.plural||(h.plural=new w);h.plural.add(a,b);D(a)&&e(b,a)}function e(a,b){h.singular||(h.singular=new w);h.singular.add(a,b)}function m(a,b){var c=RegExp(a+"$","i"),d=RegExp(b+"$","i");f(c,b);f(d,b);e(d,a);e(c,a)}function da(){L("equipment information rice money species series fish deer sheep jeans".split(" "),
function(a){f(a)})}var g,t="undefined"!==typeof global&&global.Object===Object?global:this,ea="undefined"!==typeof module&&module.f,y=!1,q={},G={},A=Object.defineProperty&&Object.defineProperties?Object.defineProperty:X,I=F("Chainable"),J=Object.getOwnPropertyNames,Y=Object.prototype.toString,Z=Object.prototype.hasOwnProperty;(function(){g=t.Sugar;if(!g){g=function(a){n(g,function(b,c){p(q,c)&&b.extend(a)});return g};if(ea)module.f=g;else try{t.Sugar=g}catch(a){}n("Object Number String Array Date RegExp Function".split(" "),
function(a){E(a)});l(g,"extend",g);l(g,"toString",S);l(g,"createNamespace",E);l(g,"util",{hasOwn:p,getOwn:B,setProperty:l,classToString:v,defineProperty:A,forEachProperty:n,mapNativeToChainable:z})}})();var M=g.String,p=g.util.hasOwn,B=g.util.getOwn,l=g.util.setProperty,v=g.util.classToString,A=g.util.defineProperty,n=g.util.forEachProperty,z=g.util.mapNativeToChainable,D,N=function(a){return function(b,c,d){b[a](c,d)}}("defineInstance"),h={};(function(){function a(a){a&&K(new a,"Object")}D=function(){return function(a){var b=
typeof a;return"string"===b||"object"===b&&K(a,"String")}}();a();a();a();Array.isArray||a();a();a("undefined"!==typeof Set&&Set);a("undefined"!==typeof Map&&Map);(function(){L("Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" "),function(){})})()})();var ca=/(^|_)([^_]+)/g;N(M,{dasherize:function(a){return C(a).replace(/_/g,"-")},underscore:function(a){return C(a)},camelize:function(a,b){return ba(a,b)}});var w,O;N(M,{pluralize:function(a,b){a=String(a);return 1===b||0===
a.length?a:O("plural",a)}});(function(){w=function(){this.map={};this.rules=[]};w.prototype={add:function(a,b){D(a)?this.map[a]=b:this.rules.unshift({c:a,h:b})},g:function(a){var b,c;a=a.split(" ");b=a.length-1;c=a[b];a[b]=this.find(c)||this.i(c);return a.join(" ")},find:function(a){return B(this.map,a)},i:function(a){for(var b=0,c;c=this.rules[b];b++)if(c.c.test(a)){a=a.replace(c.c,c.h);break}return a}}})();(function(){O=function(a,b){return h[a]&&h[a].g(b)||b};f(/$/,"s");f(/s$/i,"s");f(/(ax|test)is$/i,
"$1es");f(/(octop|fung|foc|radi|alumn|cact)(i|us)$/i,"$1i");f(/(census|alias|status|fetus|genius|virus)$/i,"$1es");f(/(bu)s$/i,"$1ses");f(/(buffal|tomat)o$/i,"$1oes");f(/([ti])um$/i,"$1a");f(/([ti])a$/i,"$1a");f(/sis$/i,"ses");f(/f+e?$/i,"ves");f(/(cuff|roof)$/i,"$1s");f(/([ht]ive)$/i,"$1s");f(/([^aeiouy]o)$/i,"$1es");f(/([^aeiouy]|qu)y$/i,"$1ies");f(/(x|ch|ss|sh)$/i,"$1es");f(/(tr|vert)(?:ix|ex)$/i,"$1ices");f(/([ml])ouse$/i,"$1ice");f(/([ml])ice$/i,"$1ice");f(/^(ox)$/i,"$1en");f(/^(oxen)$/i,"$1");
f(/(quiz)$/i,"$1zes");f(/(phot|cant|hom|zer|pian|portic|pr|quart|kimon)o$/i,"$1os");f(/(craft)$/i,"$1");f(/([ft])[eo]{2}(th?)$/i,"$1ee$2");e(/s$/i,"");e(/([pst][aiu]s)$/i,"$1");e(/([aeiouy])ss$/i,"$1ss");e(/(n)ews$/i,"$1ews");e(/([ti])a$/i,"$1um");e(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$/i,"$1$2sis");e(/(^analy)ses$/i,"$1sis");e(/(i)(f|ves)$/i,"$1fe");e(/([aeolr]f?)(f|ves)$/i,"$1f");e(/([ht]ive)s$/i,"$1");e(/([^aeiouy]|qu)ies$/i,"$1y");e(/(s)eries$/i,"$1eries");e(/(m)ovies$/i,
"$1ovie");e(/(x|ch|ss|sh)es$/i,"$1");e(/([ml])(ous|ic)e$/i,"$1ouse");e(/(bus)(es)?$/i,"$1");e(/(o)es$/i,"$1");e(/(shoe)s?$/i,"$1");e(/(cris|ax|test)[ie]s$/i,"$1is");e(/(octop|fung|foc|radi|alumn|cact)(i|us)$/i,"$1us");e(/(census|alias|status|fetus|genius|virus)(es)?$/i,"$1");e(/^(ox)(en)?/i,"$1");e(/(vert)(ex|ices)$/i,"$1ex");e(/tr(ix|ices)$/i,"trix");e(/(quiz)(zes)?$/i,"$1");e(/(database)s?$/i,"$1");e(/ee(th?)$/i,"oo$1");m("person","people");m("man","men");m("human","humans");m("child","children");
m("sex","sexes");m("move","moves");m("save","saves");m("goose","geese");m("zombie","zombies");da()})()}).call(this);